### ISSUE TITLE
Is it possible to adapt VoltaML to Stable Diffusion Inpainting model?

### ISSUE THREAD

**Issue by tunahansalih** [VoltaML/voltaML-fast-stable-diffusion#10]
I want to try VoltaML on ([stable diffusion inpainting](https://github.com/runwayml/stable-diffusion#inpainting-with-stable-diffusion)) model. What changes should I make to the conversion scripts for VoltaML to work on Inpainting models?

**Comment by VoltaML** [comment]
That too. Our first priority is giving fundamentally faster SD. Once done, we'll add more features.
