### ISSUE TITLE
[Bug]: PyTorch model,  anyway to force to run in FP32?

### ISSUE THREAD

**Issue by yi** [VoltaML/voltaML-fast-stable-diffusion#108]
### Describe the bug

hi, just tried fast-stable-diffusion, the UI is great and intuitive :+1: 

The problem I met is: I cant find a setting to force the program run in FP32. And It seems to run in FP16 by default, which is extremely slow on the gpu I'm using (1:32). 

Could there be an command line argument, like the `--no-half` and `--no-half-vae` in A111111 ?

---

I've truned on `USE FP32` in settings > API. But it still run in FP16

### Reproduction

just run `./voltaml-manager`

### Expected behavior

some sort of command line argument, like the `--no-half` and `--no-half-vae` in A111111 ?

### Installation Method

Local

### Branch

Main

### System Info

Linux

### Logs

```bash
20:46:29 | core.config.config | INFO » Loading configuration from data/settings.json
20:46:29 | core.config.config | INFO » data/settings.json not found, creating a new one
20:46:29 | core.config.config | INFO » Saving configuration to data/settings.json
20:46:29 | core.config.config | INFO » Configuration saved to data/settings.json
20:46:29 | __main__ | INFO » Device: cuda:0
>>>>> 20:46:29 | __main__ | INFO » Precision: FP16
20:46:29 | api.app | INFO » No FastAPI Analytics key provided, skipping
INFO:     Started server process [3118742]

---

[After truned on `USE FP32` in settings > API. But it still run in FP16]

INFO:     127.0.0.1:58916 - "GET /api/models/loaded HTTP/1.1" 200 OK
21:13:04 | core.inference.pytorch | INFO » Loading v1-5-pruned-emaonly.safetensors with f16
21:13:04 | core.inference.functions | INFO » Loading v1-5-pruned-emaonly.safetensors with f16
21:13:04 | core.inference.functions | INFO » Loading model as safetensors
```

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by Stax124** [comment]
It should be patched in the latest release. Can you please try again on the newest patch?
