### ISSUE TITLE
[Feature]: Support A10 or V100 accelerate

### ISSUE THREAD

**Issue by lucasjinreal** [VoltaML/voltaML-fast-stable-diffusion#109]
### Is your feature request related to a problem? Please describe.

Any demos on support A10 or V100 accelerattion?

### Describe the solution you'd like

Demos deploy cases would be very good.

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
I haven't tried volta on those GPUs yet, but they should work fine. If you need to deploy it, I would use Docker (next major release today or tomorrow - probably wait for that).

You can find some examples in docs, but some parts of documentation might be outdated.

**Comment by lucasjinreal** [comment]
@Stax124 Looks like experiments all done on A100 or H100, for some old GPU like v100 or lower class A10, will aitempalte version have speed up compares with diffusers?

**Comment by Stax124** [comment]
> @Stax124 Looks like experiments all done on A100 or H100, for some old GPU like v100 or lower class A10, will aitempalte version have speed up compares with diffusers?

It definitely should but it needs testing as well - feel free to rent a VPS on Vast.ai and try it. It should stay under $1 for testing both of them
