### ISSUE TITLE
[Bug]: AITemplate is missing completely in the Model Manager

### ISSUE THREAD

**Issue by cleverestx** [VoltaML/voltaML-fast-stable-diffusion#112]
### Describe the bug

AITemplate is missing completely in the Model Manager (it's not there at all, nada, zip, zilch)

### Reproduction

Click the models icon/page. Not there.

### Expected behavior

It should be there. Stuff should be sorted alphabetically as well, in here and all other pages showing models...

### Installation Method

Local

### Branch

Experimental

### System Info

Windows 11 Pro (retail)
Python 3.10
Latest experimental build of VoltML (WSL)

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by Stax124** [comment]
Added in bdc7fc7
