### ISSUE TITLE
[Feature]: Eliminate the gluing of received frames with a Batch Count greater than 1.

### ISSUE THREAD

**Issue by Dmitri-Demenko** [VoltaML/voltaML-fast-stable-diffusion#113]
### Is your feature request related to a problem? Please describe.

When generating pictures, I set Batch Count greater than one and get an additional picture on which all the pictures are glued into one. It is necessary to remove this gluing of pictures.

### Describe the solution you'd like

Get as many cards as specified in the Batch Count. Without a glued frame.

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
Added option to disable this behavior in the settings, effective after d14a7022c1f02bcf9deb92fb92d76e5c74d6749b

**Comment by Dmitri-Demenko** [comment]
Thank you!
