### ISSUE TITLE
[Bug]: Adding new jobs too quickly (or during loading) breaks the job queue

### ISSUE THREAD

**Issue by aaronsantiago** [VoltaML/voltaML-fast-stable-diffusion#115]
### Describe the bug

[Error log](https://github.com/VoltaML/voltaML-fast-stable-diffusion/files/12050738/message.1.txt)

I'm not sure if this is specific to controlnet, but when adding jobs to the queue too quickly the job queue breaks down and volta refuses to accept any more requests. This window where requests break the job queue is very wide while controlnet is loading specifically, and is the easiest way to trigger the bug.

### Reproduction

1. Load a model
2. Do a controlnet request
3. Immediately do a second controlnet request (before controlnet is finished loading)

or

1. Send two controlnet requests within about .3 seconds of each other

### Expected behavior

Jobs are added to the queue and are processed when Volta is ready

### Installation Method

Local

### Branch

Experimental

### System Info

WSL, Python 3.9, latest experimental

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by gabe56f** [comment]
Support for concurrent jobs was removed in 3df17651c3e1369a5d123cb0de690a126a9117a7
