### ISSUE TITLE
Performance Statistics: What does Memory percentage mean?

### ISSUE THREAD

**Issue by asthinasthi** [VoltaML/voltaML-fast-stable-diffusion#118]
I see this 
![image](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/4577101/93eabfd1-7f39-4cea-839f-c655ba18dd1a)

Does this mean the App is only able to use 36% of total available VRAM?

**Comment by Stax124** [comment]
> I see this ![image](https://user-images.githubusercontent.com/4577101/253729126-93eabfd1-7f39-4cea-839f-c655ba18dd1a.png)
> 
> Does this mean the App is only able to use 36% of total available VRAM?

This is basically Task Manager / Nvidia-smi in the browser. It is there for folks that run Volta in the cloud so that they can monitor the usage and memory

**Comment by asthinasthi** [comment]
Just to close this.

I have a RTX 3060 12GB. This shows how much VRAM is being allocated to VoltaML by the OS. 
The Memory maxes to 10GB in my case. Utilization of this _allocated_ memory fluctuates whenever I generate images.

**Comment by Stax124** [comment]
> Just to close this.
> 
> I have an RTX 3060 12GB. This shows how much VRAM is being allocated to VoltaML by the OS. The Memory maxes to 10GB in my case. Utilization of this _allocated_ memory fluctuates whenever I generate images.

This just shows raw data from the GPU, it has nothing to do with Volta itself. As I said, this is more like a monitoring utility (Windows Task Manager, Nvidia-smi, nvtop, btop).
