### ISSUE TITLE
pyamdgpuinfo utilisation polling optimisation

### ISSUE THREAD

**Issue by mark9064** [VoltaML/voltaML-fast-stable-diffusion#121]
https://github.com/VoltaML/voltaML-fast-stable-diffusion/blob/11de3acfe36b1b077d473fed56fb4766e91e8789/api/websockets/manager.py#L58

Just as a heads up, you don't actually need utilisation polling threads as you're not using `query_utilisation` (and for compute it doesn't make sense so you're good here)
Should save you a little CPU overhead :)
More info [here](https://github.com/mark9064/pyamdgpuinfo/blob/27763ecba50ef3511848cdebb4666ad3e429b74c/pyamdgpuinfo/_pyamdgpuinfo.pyx#L334)

**Comment by gabe56f** [comment]
Fixed in commit 12fe582, thanks man, appreciate it :)
