### ISSUE TITLE
[Bug]: Doesn't support AMD

### ISSUE THREAD

**Issue by MidnightKittenCat** [VoltaML/voltaML-fast-stable-diffusion#129]
### Describe the bug

It's been a few months and AMD still isn't supported whats going on?

### Reproduction

Using an AMD gpu

### Expected behavior

It working

### Installation Method

Local

### Branch

Main

### System Info

3.11, Ubuntu, Current

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by Stax124** [comment]
Send me logs or an AMD GPU, the latter one would be better

**Comment by MidnightKittenCat** [comment]
> Send me logs or an AMD GPU, the latter one would be better

The only thing it gives me is 

`[ERROR] AMD not supported yet
`

**Comment by Stax124** [comment]
That is just the installer, you can install manually with git clone and creating a venv

**Comment by Stax124** [comment]
Volta Manager was made to make installation easier, but since no dev has AMD gpu, we cannot just guess what will work and run with it

**Comment by MidnightKittenCat** [comment]
Gotcha I'll give it a shot after this, thanks for the quick response.

**Comment by MidnightKittenCat** [comment]
Perhaps I'm doing something wrong
![image](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/66114416/7cf473fd-9c78-4c08-97d3-2388c0083ee8)

It's been like this for the past 10 minutes, I've even got the proper pytorch installed (the rocm version)

**Comment by MidnightKittenCat** [comment]
![image](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/66114416/14aa57f7-7c7d-4fe0-84c3-932fdf9b2b06)

Doesn't seem to be utilising 99% of my gpu.

**Comment by Stax124** [comment]
It seems to be if you look at the wattage. We just don't have those GPUs so progress bar scales are off. This is the point where all I can say is "AMD, send us a GPU" or this will just stay like it - we just don't know what is wrong. I would probably use something else than Volta for AMD gpus.

**Comment by MidnightKittenCat** [comment]
That's a shame I really wanted to use it, well if there's anything I can do like testing builds for amd let me know.

**Comment by MidnightKittenCat** [comment]
If it helps it takes longer than the cpu would to generate an image.

**Comment by Stax124** [comment]
Yeah, I have no idea why it is doing that, but as I said, I cannot test it. You can give this one a shot: https://github.com/nod-ai/SHARK. From what I heard, it should be ready for AMD cards.

We want to provide full AMD support, but that probably isn't happening unless Gabe or I get one.

Closing this as we cannot help further.

**Comment by Boom-Hacker** [comment]
don't worry,i have 6750xt and 7600,i will port ROCM/AITemplate to radeon game video cards,now only vae not work

**Comment by MidnightKittenCat** [comment]
> don't worry,i have 6750xt and 7600,i will port ROCM/AITemplate to radeon game video cards,now only vae not work

Sounds great! any idea as to when we can expect this?

**Comment by MidnightKittenCat** [comment]
> don't worry,i have 6750xt and 7600,i will port ROCM/AITemplate to radeon game video cards,now only vae not work

Any update?
