### ISSUE TITLE
python3 volta_accelerate.py --onnx_trt=trt "$@"

### ISSUE THREAD

**Issue by kohlernsven** [VoltaML/voltaML-fast-stable-diffusion#14]
Sorry for bothering. I am not that of a code-man. Seems i get nearer using your docker image but i still keep a bunch of errors when i try to tune a model with it. last error i got was

optimize.sh: line 1:  4939 Segmentation fault      python3 volta_accelerate.py --onnx_trt=onnx "$@"
optimize.sh: line 2:  4959 Segmentation fault      python3 volta_accelerate.py --onnx_trt=trt "$@"

any idea what i can do to get it to work?

**Comment by VoltaML** [comment]
Can you please share the screenshot of the error? Also, can you give me the environment details - GPU, CUDA, CuDNN etc?
