### ISSUE TITLE
[Feature]: macOS support

### ISSUE THREAD

**Issue by nikitavoloboev** [VoltaML/voltaML-fast-stable-diffusion#140]
### Is your feature request related to a problem? Please describe.

Would love to use this but did not see macOS install instructions. Can it run on macOS?

### Describe the solution you'd like

macOS working

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
Same story as here: https://github.com/VoltaML/voltaML-fast-stable-diffusion/issues/129
