### ISSUE TITLE
[Feature]: Ability to enable Highres fix with Dynamic AITemplate model

### ISSUE THREAD

**Issue by Dmitri-Demenko** [VoltaML/voltaML-fast-stable-diffusion#144]
### Is your feature request related to a problem? Please describe.

Highres fix dont work with Dynamic AITemplate

### Describe the solution you'd like

Ability to enable Highres fix with Dynamic AITemplate model

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
Added in bb2a25d, on the track to be merged into the main branch next release
