### ISSUE TITLE
[Feature]: how can i call Highres fix on api mode

### ISSUE THREAD

**Issue by blueming333** [VoltaML/voltaML-fast-stable-diffusion#147]
### Is your feature request related to a problem? Please describe.

can i call Highres fix on api mode?

### Describe the solution you'd like

 how can i call Highres fix on api mode

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
Example API call body:

```json
{
  "data": {
    "prompt": "1girl, sakura tree, long hair, dress",
    "scheduler": 8,
    "id": "test",
    "negative_prompt": "nsfw,(worst quality:2.0),(low quality:1.4),(bad-hands:0.2), easynegative, verybadimagenegative_v1.3, badhandv4, ng_deepnegative_v1_75t",
    "width": 512,
    "height": 512,
    "steps": 25,
    "guidance_scale": 7,
    "self_attention_scale": 0,
    "use_karras_sigmas": false,
    "seed": 1234,
    "batch_size": 1,
    "batch_count": 1
  },
  "model": "Azher/Anything-v4.5-vae-fp16-diffuser",
  "websocket_id": "",
  "save_image": true,
  "flags": {
    "highres_fix": {
      "scale": 2,
      "latent_scale_mode": "bislerp-tortured",
      "strength": 0.7,
      "steps": 50,
      "antialiased": true
    }
  }
}
```

The only thing needed is to pass in the extra flag `highres_fix`. This flag only works on Text2Image calls.

Type reference (frontend/src/settings.ts -> line 32):

![image](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/60222162/cd9e258f-5f31-40e4-91c4-1a9001c7d460)

If you have more questions regarding the API, feel free to join our discord, we can usually help much quicker there (or just post here, I do not mind)
