### ISSUE TITLE
[Bug]: jpeg format does not work

### ISSUE THREAD

**Issue by blueming333** [VoltaML/voltaML-fast-stable-diffusion#148]
### Describe the bug

i set Image extension to JPEG,but download image format is webp。

### Reproduction

set Image extension to JPEG,
general a image,
download

### Expected behavior

jpg has stronger universality

### Installation Method

Local

### Branch

Experimental

### System Info

python3.10  linux  ubuntu22

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by Stax124** [comment]
Patched in 253b111 - available on experimental, on track to be merged into main with next major release
