### ISSUE TITLE
[Feature]: Colab Support

### ISSUE THREAD

**Issue by nbalive2k** [VoltaML/voltaML-fast-stable-diffusion#149]
### Is your feature request related to a problem? Please describe.

Is possible to make this compatible with google colab and others notebooks
like kaggle and saturn cloud?

### Describe the solution you'd like

Support for cloud notebooks

### Describe alternatives you've considered

 google colab, kaggle. saturn cloud

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
This should work for basic inference, feel free to extend it: https://colab.research.google.com/drive/1g8wNGhFZGFD3YGqeO3wKBdPH3ixfZOGI?usp=sharing
