### ISSUE TITLE
[Feature]: Add the ability to connect the model at program startup using an argument. 

### ISSUE THREAD

**Issue by Dmitri-Demenko** [VoltaML/voltaML-fast-stable-diffusion#151]
### Is your feature request related to a problem? Please describe.

Add the ability to connect the model at program startup using an argument. 

### Describe the solution you'd like

For example like this :
#!/bin/bash
python3 main.py --log-level=${LOG_LEVEL} --host --model /model

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
Added in c81c3f7f7585a57eee01fcd932c96f1c075ab1c7, solved by adding this option to the API settings, it takes an array at the backend, so it should be possible to load multiple models. I will have a look at loading Vae automatically as well soon.
