### ISSUE TITLE
[Feature]: Does VoltaMl support deforum?

### ISSUE THREAD

**Issue by otorre1** [VoltaML/voltaML-fast-stable-diffusion#152]
### Is your feature request related to a problem? Please describe.

Nop

### Describe the solution you'd like

I didn't find the answer anywhere

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
There is no support for animation inside Volta and it is not planned as it would certainly introduce a lot more complexity.
