### ISSUE TITLE
[Feature]: Allow loading of models from subfolders of the data/models directory.

### ISSUE THREAD

**Issue by sh1ny** [VoltaML/voltaML-fast-stable-diffusion#169]
### Is your feature request related to a problem? Please describe.

I have a large library of models and i can't use it, because i have them in subfolders.
Here's what i have:

models/SD1.5/
models/SD2.1/
models/SDXL

The same goes for loras and everything else that is specific to a certain version of SD.
This works fine in every other SD UI - a1111, comfyui, invokeai etc.

### Describe the solution you'd like

The ability to read/load models from subfolders. Here's how it looks in StabilityMatrix:

https://i.imgur.com/5d0FBWS.png

### Describe alternatives you've considered

I could just move them to the root folder, but then i'd have to keep guessing which model is which version.

### Additional context

None.

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
I will look into it when I get some free time. It shouldn't be that hard to implement. Probably expect something on the experimental branch this week.

**Comment by Stax124** [comment]
Added in 5c2389b, give it a try when you have time. If you find any bugs, you can just report them here or in our discord.

If you are on experimental, all you need to do is `git pull` or update it via your manager. It will be merged into the main branch in the future. Closing for now.
