### ISSUE TITLE
[Bug]: Intel Arc Torch issue

### ISSUE THREAD

**Issue by gmbhneo** [VoltaML/voltaML-fast-stable-diffusion#173]
### Describe the bug

Upon starting using the intel command, I get the following error:

`Looking in links: https://developer.intel.com/ipex-whl-stable-xpu
ERROR: Could not find a version that satisfies the requirement torch==1.13.0a0 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1)
ERROR: No matching distribution found for torch==1.13.0a0
Traceback (most recent call last):
  File "D:\SMatrix\Data\Packages\VoltaML\main.py", line 334, in <module>
    args = checks()
  File "D:\SMatrix\Data\Packages\VoltaML\main.py", line 299, in checks
    install_deps(args_with_extras.pytorch_type if args_with_extras.pytorch_type else -1)
  File "D:\SMatrix\Data\Packages\VoltaML\core\install_requirements.py", line 264, in install_deps
    subprocess.check_call(c.install_command)  # type: ignore
  File "subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['D:\\SMatrix\\Data\\Packages\\VoltaML\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'torch==1.13.0a0', 'torchvision==0.14.1a0', 'intel_extension_for_pytorch==1.13.120+xpu', '-f', 'https://developer.intel.com/ipex-whl-stable-xpu']' returned non-zero exit status 1.`

### Reproduction

Simply start with intel command prompt and wait a few seconds.

### Expected behavior

Simply download and install the necessary packages.

### Installation Method

Local

### Branch

Main

### System Info

Windows, Py 3.10, latest version

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by gabe56f** [comment]
Can you check if this is also present on `experimental`?

Run `git checkout experimental` in the root folder of Volta

**Comment by gmbhneo** [comment]
Yes, also happens on experimental.

**Comment by Stax124** [comment]
Try running this from the terminal inside the Volta root folder:

```
.\venv\Scripts\activate.bat
pip install torch==2.0.1a0 torchvision==0.15.2a0 intel_extension_for_pytorch==2.0.110+xpu -f https://developer.intel.com/ipex-whl-stable-xpu
```
or replace `.bat` with `.ps1` if you use PowerShell as your main shell.

This should install the necessary stuff and satisfy the torch requirement so that installation can move on. 

Ref: https://github.com/intel/intel-extension-for-pytorch?tab=readme-ov-file#gpu-version

**Comment by gmbhneo** [comment]
![grafik](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/16648908/a4bba66d-e32f-4056-868c-051bd81ce2ec)

The error at least changed a bit 🤔

**Comment by Stax124** [comment]
Oh, you used stability matrix... give me some time, I need to check how their Venv works. It might have not activated properly

**Comment by Stax124** [comment]
Try another update, you will need to set `--pytorch-type=intel` in the Matrix as an extra command

**Comment by gmbhneo** [comment]
What do you mean by "try another update"? I've been using the `--pytorch-type=intel` already

**Comment by Stax124** [comment]
I just sent another patch upstream, just update Volta in Stability Matrix

**Comment by gmbhneo** [comment]
Already did, that's the screenshot after updating, sorry, was too fast posting.

**Comment by Stax124** [comment]
Should be patched now

**Comment by Stax124** [comment]
Maybe patched

**Comment by gmbhneo** [comment]
![grafik](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/16648908/be4e8355-0a37-4485-9530-0a084e703083)
![grafik](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/16648908/216349a5-5aec-44ed-8c40-dc20f818ccd1)

this is heppening after selecting my GPU, which is not selected by default

**Comment by Stax124** [comment]
This is something with the package itself, not much we can do there. The only option I can think of right now is just to wait for official support from Intel. At least on Windows that is.
