### ISSUE TITLE
[Feature]: Independant Image Browser

### ISSUE THREAD

**Issue by daisseur** [VoltaML/voltaML-fast-stable-diffusion#177]
# An Independant Image Browser
Just make sure that the image browser can be launched in the outputs folder directly without going through the ui by starting VoltML, which can be useful if the files are on a server and you want to explore them.

>The same Image browser or a best one
![image](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/100715068/9ec653f1-c87b-4ec2-a62e-8f04295d3c3a)

**Comment by Stax124** [comment]
Our image browser is part of the UI/API and cannot be carved out as an independent application
