### ISSUE TITLE
Voltaml-manager not working 

### ISSUE THREAD

**Issue by KintCark** [VoltaML/voltaML-fast-stable-diffusion#182]
I think the linux file is in wrong format it downloads as a bin file and when I try to launch ./voltaml-manager it says file not found

I did chmod+x but it still doesn't detect the file. Can u please fix this. Please respond

**Comment by Stax124** [comment]
Use StabilityMatrix instead: https://voltaml.github.io/voltaML-fast-stable-diffusion/installation/stability-matrix

It is easier to work with and has a GUI
