### ISSUE TITLE
PyTorch model should not default to SD 1.4

### ISSUE THREAD

**Issue by wywywywy** [VoltaML/voltaML-fast-stable-diffusion#2]
https://github.com/VoltaML/voltaML-fast-stable-diffusion/blob/e865e25d2f694bd5863da6333c6b3f29be8f6088/pytorch_model.py#L8

Everything else in the repo references SD 1.5, so PyTorch should use SD 1.5 as well and not 1.4.

This may also explain why the generated images are so different using the 2 methods.

**Comment by VoltaML** [comment]
Changed the default to v1.5 on the main branch. Please check.

**Comment by wywywywy** [comment]
You forgot to change the comment after the line 😁

**Comment by VoltaML** [comment]
Done. Thank you :)
