### ISSUE TITLE
Converted models produce same output

### ISSUE THREAD

**Issue by umag** [VoltaML/voltaML-fast-stable-diffusion#21]
I've converted to trt SD1.5 SD2.1 and my merge https://huggingface.co/Magistr/Magmix
and run 
that prompt against them, 
(18 years young girl:1.4),detailed face and eyes,green eyes,female focus,silver hair,short messy hair,small breasts,flat chest,(blue sneakers:1.2),(black bike shorts:1.2),full body,fooling around,standing, wolf years, wolf tail, animal tail, grey croptop,red jacket, riverside, ruins, old bridge,(yellow socks:1.2),

got same images in output from all 3 trt models

**Comment by harishprabhala** [comment]
So you're getting the same outputs for 1.5 and 2.1 with TRT? 

voltaML doesn't have TRT support yet.

**Comment by uMag** [comment]
To clarify trt=accelerate in voltaml, as I see you a compiling models to tensorRT format,
yes correct same outpusts for SD 1.5 2.1 and other merge based on SD 1.5

**Comment by 78Alpha** [comment]
My assumption is that it is using the regular TRT code, which is hard coded for the 1.5 model. Any model that gets accelerated would have its weights replaced with the base model, turning it into the base model.

**Comment by Stax124** [comment]
Closing as TensorRT support was deprecated in favor of AITemplate
