### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chavinlo** [VoltaML/voltaML-fast-stable-diffusion#22]
First of all, thank you for making compilation much simpler.

However, I think proper documentation is needed for better adoption of this technology

More specifically the `infer_trt` function on https://github.com/VoltaML/voltaML-fast-stable-diffusion/blob/f3db5838bcba7a9f6ae207061ac4ec9ba790b45f/volta_accelerate.py#L446

I would also like to make sure that what all the "convertor" does is compile it into tensorRT.

Thank you.

**Comment by Stax124** [comment]
Project has been migrated to AITemplate since this request was posted. AIT has similar pipeline to diffusers, so therefore should be much easier to read.
