### ISSUE TITLE
Quietly fails and closes

### ISSUE THREAD

**Issue by 78Alpha** [VoltaML/voltaML-fast-stable-diffusion#26]
Have been testing it out to see what it tries to do to load memory. I have an RTX 3070 8 GB and wanted to see how much memory it used before failing, however, it has not used any VRAM outside of the 2.4 GB to load the model. For RAM, it jumps up 6 GB but then quietly fails. Barely touches the 48 GB RAM avilable.

By quietly fails, I mean that it just doesn't do anything, or say anything.

Example:

```
if causal_attention_mask.size() != (bsz, 1, tgt_len, src_len):
A:\Anaconda\envs\voltaml\lib\site-packages\transformers\models\clip\modeling_clip.py:262: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
(voltaml) PS H:\Downloads\voltaML-fast-stable-diffusion-main>
```

Output directory is empty, no logs were found either.

**Comment by VoltaML** [comment]
Hi @78Alpha, we have tested it on a 8GB card and it worked. Can you please share the steps to reproduce your error?

**Comment by 78Alpha** [comment]
1. git clone https://github.com/VoltaML/voltaML-fast-stable-diffusion.git
2. Make directories output and engine if not already present
3. cd into VoltaML stable diffusion directory
4. pip install -r requirements.txt
5. After it fails to find nvtx3, copy it into Python include directory and run pip install -r requirements.txt
6. Install tensorrt from Nvidia developer page as it can't be installed from pip normally
7. Attempt to run app.py (if it fails about Unicode or something, downgrade flask to a version below 3)
8. Go to link provided by successfully launched app.py
9. Go to accelerate tab
10. Accelerate any model
11. Proceeds to accelerate
12. Fails halfway through with no error or any excessive resource utilization

I think I forgot to mention that I have been trying to run on Windows. WSL2 did not work. No ONNX mid-model is made, no log files are output.

**Comment by 78Alpha** [comment]
Tested it out on a Nvidia Tesla P40 as well, it does the same thing, except it takes longer to fail, but fails at the same point.

**Comment by 78Alpha** [comment]
From some more looks into it, it seems to load a model but print it as a string instead of saving it.

**Comment by Stax124** [comment]
> From some more looks into it, it seems to load a model but print it as a string instead of saving it.

I will look into it tomorrow. I will contact you if I need more info. Thanks for the leads.

Also if I patch this, then it should arrive on `experimental` branch.

**Comment by 78Alpha** [comment]
The last bit of relevant info I have comes from https://github.com/onnx/onnx/issues/2201

**Comment by 78Alpha** [comment]
I got the original TRT repo to work for the base 1.5 model. It needs a compiled from source DLL to load as the standard TRT release doesn't support stable diffusion. It didn't compile for me but someone else had a DLL, used it, and it loaded up the model for VoltaML as well. The quality was extremely poor though...

Models based on the Anime or Non-1.5 base did not convert at all. They gave a CLIP error stating that none of the layers/weights would be used so it generated nothing. Someone got anythingv3 converted, however, it can't be recompiled for a different platform, as it throws the CLIP error.

I have been trying with WSL2 as well but it is horribly fragile. I CTRL-C'ed a dreambooth training and it deleted my CUDA install for some reason. But that is out of scope for this issue.

**Comment by Stax124** [comment]
Closing as TensorRT support was deprecated in favor of AITemplate
