### ISSUE TITLE
Fine tuned model quality degrade after compiling to TRT

### ISSUE THREAD

**Issue by jd0713** [VoltaML/voltaML-fast-stable-diffusion#29]
Hi I found your code works really good. 
Compile went smooth, but I found that my fine tuned model quality goes down when infer with compiled TRT engines.
Do you have experience of quality change after compile?  
Or is it okay with your models?

**Comment by VoltaML** [comment]
Hi. We have not experienced any quality change. How do you define quality degradation? Any supporting examples you can share?

**Comment by jd0713** [comment]
Yes, sure. I will upload sample images soon.

**Comment by VoltaML** [comment]
Which GPU are you testing this on? Are the parameters same for both PT and TRT inference?
