### ISSUE TITLE
ENV CUDA_MODULE_LOADING=LAZY

### ISSUE THREAD

**Issue by ternaus** [VoltaML/voltaML-fast-stable-diffusion#32]
Docker is built with cuda 11.6

While lazy loading is supported only in cuda 11.7+

**Comment by Stax124** [comment]
New WebUI will be running Cuda 11.7, @riteshgangnani10 probably added it for future use, is it conflicting somewhere for now?

**Comment by ternaus** [comment]
It may happen that https://github.com/VoltaML/voltaML-fast-stable-diffusion/issues/31 could be mitigated if lazy loading is enabled.

Less GPU memory used => more TRT optimizations could be implemented => and the compilation will go without error.

**Comment by Stax124** [comment]
Ok, thanks for reporting, I will let TRT devs know

**Comment by Stax124** [comment]
Fixed on experimental branch. Thanks for reporting it. Closing
