### ISSUE TITLE
Tutorial for benchmark

### ISSUE THREAD

**Issue by ternaus** [VoltaML/voltaML-fast-stable-diffusion#33]
Could you please add a tutorial on how to run the benchmark?

**Comment by Stax124** [comment]
> Could you please add a tutorial on how to run the benchmark?

Hi, the benchmark from the main branch will be probably removed or reworked with the release of the new API and WebUI. For this reason, I do not see any benefits in creating documentation for it now.

**Comment by ternaus** [comment]
For example, that is how we do it in Albumentations:

https://github.com/albumentations-team/albumentations/#benchmarking-results

People often thanked us for providing an option to check the results on their hardware.

**Comment by Stax124** [comment]
I get that but there are now so many things that we need to implement and take care of. If we manage to create a benchmark, we will of course make some documentation for it. But for now, there is no time that we can spare for such small things.

This doesn't mean that we wouldn't do that, but we just don't have enough people to make it right. And I want to do it right.
