### ISSUE TITLE
How to delete this?

### ISSUE THREAD

**Issue by StingPax** [VoltaML/voltaML-fast-stable-diffusion#35]
Hello there, after i installed it and tinker with it with no results i found out that my drive C is full from this, how do i delete it? Why didnt it got installed in the folder i run it from?

**Comment by Stax124** [comment]
> Hello there, after i installed it and tinker with it with no results i found out that my drive C is full from this, how do i delete it? Why didnt it got installed in the folder i run it from?

Hello, we are using docker for running this container, if you are on windows then you should be able to delete this container in the Docker Hub (images section)

We are sorry that our container didn't work for you. We are now rewriting the project on the `experimental` branch, so you might be able to run this in few weeks if you want to try again.

I will also try to include Uninstall and Cleanup section in the new readme.

Have a nice day
