### ISSUE TITLE
CLIP model in models.py cannot be changed

### ISSUE THREAD

**Issue by axel-havard** [VoltaML/voltaML-fast-stable-diffusion#37]
Hi,

In models.py file, the CLIP class can only load a default CLIP (I copy/paste the current code bellow). Shouldn't it be self.model_path instead of "openai/clip-vit-large-patch14" ? VAE and UNET are set to the correct self.model_path.

class CLIP(BaseModel):
    def get_model(self):
        return CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(self.device)

Thanks !

**Comment by axel-havard** [comment]
Same issue for CLIP tokenizer in volta_accelerate.py line 316, it is set to "openai/clip-vit-large-patch14" instead of going to a custom model_path

**Comment by 78Alpha** [comment]
This part of the recompiling modules I have been having. Changing the CLIP to anything else that is not like the base 1.5 throws more errors.

**Comment by Stax124** [comment]
I will personally try to create an AITemplate model class because I spent more than 60+ hours on debugging an nullptr error with TRT and still no luck. It might not be as fast but I hope that there will be more compatibility.

**Comment by Stax124** [comment]
Closing as TensorRT support was deprecated in favor of AITemplate. AITemplate supports custom CLIP.
