### ISSUE TITLE
Why compute >=7.5 required and 7.0 not supported..

### ISSUE THREAD

**Issue by oscarbg** [VoltaML/voltaML-fast-stable-diffusion#39]
Have a Titan V which is cc 7.0.. any reason why not supported V100 cards?
Curious as this project is called “Volta”..
What specific cc7.5 features needs? 
Thanks..

**Comment by Stax124** [comment]
That requirement is set by Nvidia from what I know, but, feel free to use my new AITemplate integration, it's not officially out yet but you can try it now. There are instructions on our Discord server (announcements channel).
