### ISSUE TITLE
Question: about FP8 support for Ada and Hopper..

### ISSUE THREAD

**Issue by oscarbg** [VoltaML/voltaML-fast-stable-diffusion#41]
Hi,
Just asking how difficult will be to add FP8 support to VoltaML once TensorRT supports new FP8 format on Ada and Hopper..
What performance uplift can we expect? maybe 4090 from 80iters/s to 120 iters? Or near to 2x up to 160 iters/s..
Also would be nice to include VoltaML on H100 perf. numbers currently (beforce FP8), in case anyone can get access to..

Thanks..

**Comment by oscarbg** [comment]
Edit: I asked about tensorrt fp8 support here:
https://github.com/NVIDIA/TensorRT/issues/2730

**Comment by Stax124** [comment]
Hey @oscarbg, tbh I just postponed the TensorRT pipeline indefinitely after spending hundreds of hours debugging it on my sytem, current development and focus is on AITemplates - so - even if I manage to somehow get TRT up and running again, there is almost zero chance that we can just upgrade all the dependencies (which were the issues that I was having).

If some major help comes or I get a GPU with more VRAM then I might reignite the work there - but it is highly unlikely.

Anyways, if you want to try AIT, come and join our discord, steps on how to run are in the announcement channel (or I will probably update the docs tomorrow).

(and yes, if F8 becomes possible than you are looking at about 2x speedup - with a lot of quality loss i guess)

Have a nice rest of your day.

**Comment by oscarbg** [comment]
Thanks @Stax124 for all the info..
