### ISSUE TITLE
Does this project support the acceleration of Lora and ControlNet?

### ISSUE THREAD

**Issue by liuguicen** [VoltaML/voltaML-fast-stable-diffusion#42]
If not, does anyone know how to realize it? Or it cannot be realized based on TensorRT。

**Comment by Stax124** [comment]
> If not, does anyone know how to realize it? Or it cannot be realized based on TensorRT。

I have switched Volta from TensorRT to AITemplate so there is a chance that it might be possible, but definitely not easy as far as Lora goes.

I need to look at how ControlNet works but I assume that this can be implemented without much hassle as it seems that it is detached from the UNet and VAE (but that is just a theory based on my observations, more research is needed there)
