### ISSUE TITLE
[Feature Request] Support for Real-ESRGAN and GFPGAN

### ISSUE THREAD

**Issue by JannyPvP** [VoltaML/voltaML-fast-stable-diffusion#43]
Would it be possible to implement it or doesn't it work with these special models?

**Comment by Stax124** [comment]
It is a totally separate thing so implementing it wouldn't be a problem. I wanted to do this for a while but I have so much work both on Volta and at school that I cannot give you any ETA, but I definitely want Real-ESRGAN and Latent upscale.
