### ISSUE TITLE
Process killed when using "volta_accelerate.py"

### ISSUE THREAD

**Issue by Pop115** [VoltaML/voltaML-fast-stable-diffusion#5]
Hello, I encountered a problem when trying to use volta_accelerate.py

System info:
Windows 10
Nvidia 3060Ti 8GB
i5-11400F
Using Docker Desktop with WSL2 (Ubuntu) with the voltaML Docker Container image

Here is the command and the log I got
```
root@f585f96dd9a2:/workspace/voltaML-fast-stable-diffusion# python3 volta_accelerate.py --model="runwayml/stable-diffusion-v1-5"
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.44G/3.44G [05:11<00:00, 11.0MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 743/743 [00:00<00:00, 589kB/s]
/workspace/voltaML-fast-stable-diffusion/diffusers/models/unet_2d_condition_onnx.py:274: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if any(s % default_overall_up_factor != 0 for s in sample.shape[-2:]):
/workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:182: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
/workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:187: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
/workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:109: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
/workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:122: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if hidden_states.shape[0] >= 64:
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:777: UserWarning: no signature found for <torch.ScriptMethod object at 0x7fa7a64aa040>, skipping _decide_input_format
  warnings.warn(f"{e}, skipping _decide_input_format")
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:1880: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input latent_model_input
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:1880: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input t
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:1880: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input encoder_hidden_states
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torch/onnx/_patch_torch.py:67: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1874.)
  torch._C._jit_pass_onnx_node_shape_type_inference(
/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:648: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1874.)
  _C._jit_pass_onnx_graph_shape_type_inference(
Killed
```

The last log is just "Killed" so I don't know where to investigate, maybe it's due to my graphics card not having enough VRAM?

**Comment by harishprabhala** [comment]
> Hello, I encountered a problem when trying to use volta_accelerate.py
> 
> 
> 
> System info:
> 
> Windows 10
> 
> Nvidia 3060Ti 8GB
> 
> i5-11400F
> 
> Using Docker Desktop with WSL2 (Ubuntu) with the voltaML Docker Container image
> 
> 
> 
> Here is the command and the log I got
> 
> ```
> 
> root@f585f96dd9a2:/workspace/voltaML-fast-stable-diffusion# python3 volta_accelerate.py --model="runwayml/stable-diffusion-v1-5"
> 
> Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.44G/3.44G [05:11<00:00, 11.0MB/s]
> 
> Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 743/743 [00:00<00:00, 589kB/s]
> 
> /workspace/voltaML-fast-stable-diffusion/diffusers/models/unet_2d_condition_onnx.py:274: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> 
>   if any(s % default_overall_up_factor != 0 for s in sample.shape[-2:]):
> 
> /workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:182: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> 
>   assert hidden_states.shape[1] == self.channels
> 
> /workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:187: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> 
>   assert hidden_states.shape[1] == self.channels
> 
> /workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:109: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> 
>   assert hidden_states.shape[1] == self.channels
> 
> /workspace/voltaML-fast-stable-diffusion/diffusers/models/resnet.py:122: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> 
>   if hidden_states.shape[0] >= 64:
> 
> /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:777: UserWarning: no signature found for <torch.ScriptMethod object at 0x7fa7a64aa040>, skipping _decide_input_format
> 
>   warnings.warn(f"{e}, skipping _decide_input_format")
> 
> /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:1880: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input latent_model_input
> 
>   warnings.warn(
> 
> /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:1880: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input t
> 
>   warnings.warn(
> 
> /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:1880: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input encoder_hidden_states
> 
>   warnings.warn(
> 
> /opt/conda/lib/python3.8/site-packages/torch/onnx/_patch_torch.py:67: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1874.)
> 
>   torch._C._jit_pass_onnx_node_shape_type_inference(
> 
> /opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py:648: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/passes/onnx/shape_type_inference.cpp:1874.)
> 
>   _C._jit_pass_onnx_graph_shape_type_inference(
> 
> Killed
> 
> ```
> 
> 
> 
> The last log is just "Killed" so I don't know where to investigate, maybe it's due to my graphics card not having enough VRAM?

This is CPU RAM issue. You need around 16GB RAM for ONNX conversion.

**Comment by Pop115** [comment]
I have 16GB RAM though, maybe a problem with how docker use the RAM, I'll try without it

**Comment by wywywywy** [comment]
WSL2 doesn't make use of ALL the system RAM.

See here: https://www.aleksandrhovhannisyan.com/blog/limiting-memory-usage-in-wsl-2/
