### ISSUE TITLE
Obvious Output Discrepancy between PyTorch and AITemplate inference

### ISSUE THREAD

**Issue by alvinsay** [VoltaML/voltaML-fast-stable-diffusion#55]
## Description
The output discrepancy between PyTorch and AITemplate inference is quite obvious.

According to our various testing cases, AITemplate produces lower-quality results on average, especially for human faces.

### Reproduction

Model:
[chilloutmix-ni-pruned-fp16-fix](https://civitai.com/models/6424?modelVersionId=11732)

Prompt:
```
brown hair, 1girl, solo, hand on the hip, dress, looking at viewer, smile, street
```
Negative Prompt:
```
(worst quality low quality:1.4)
```
| Parameter | Value |
|----|----|
| Height| 512|
| Width | 512|
|Sampler| DPMSolverMultiStep|
|CFG | 7|
|Batch Count |  4 |
|Batch Size| 1|
|Seed | 1191535362| 

### PyTorch Results

![bbb](https://user-images.githubusercontent.com/11836570/231118340-d9b851bc-f5dc-4f9c-8d85-9011d58ee21e.jpg)

### AITemplate Results

![ait](https://user-images.githubusercontent.com/11836570/231118508-6ee75b2d-2028-4cf5-98f5-4ba441d41b50.jpg)

### Expected behavior

PyTorch and AITemplate should produce similar results and quality.

### Branch

Experimental

### System Info

OS: Debian 11
GPU: Nvidia L4
CUDA: 12.1

### Additional context

It might be related to https://github.com/facebookincubator/AITemplate/issues/141

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Stax124** [comment]
Well the first thing why it is like that: we do not have Long Weighted Prompts for AIT yet - so your negative prompt is different

Also some samplers are non deterministic and I think this one is one of them

I will try to look at it more once I get home

**Comment by alvinsay** [comment]
Thank you for the quick response.

I tried to remove the long-weighted prompts.
More experiment results are here.

Model:
[chilloutmix-ni-pruned-fp16-fix](https://civitai.com/models/6424?modelVersionId=11732)

Prompt:
```
perfect face, girl, solo, hand on the hip, dress, looking at viewer, smile, street
```
Negative Prompt:
```
worst quality, low quality
```
| Parameter | Value |
|----|----|
| Height| 512|
| Width | 512|
|Sampler| DPMSolverMultiStep|
| Steps | 20 |
|CFG | 7|
|Batch Count |  1 |
|Batch Size| 1|
|Seed | 1197235362 | 

Their results still have significant discrepancies.

### PyTorch Results

PyTorch results are deterministic. 
The results are all the same for the same settings.

![bbb_000](https://user-images.githubusercontent.com/11836570/231322433-d367fe67-7862-465c-be29-de0cda4b65af.png)

### AITemplate Results

AITemplate Results are NOT deterministic.
The results are different but similar for the same settings.

![ait_000](https://user-images.githubusercontent.com/11836570/231322701-320ace76-d129-45ff-b618-5d5c097863ca.png)

![ait_001](https://user-images.githubusercontent.com/11836570/231322715-c1f632bc-6092-462a-83a2-5a54bd332795.png)

![ait_002](https://user-images.githubusercontent.com/11836570/231322737-6db1a9c7-38c6-452c-8682-4068f93f5e50.png)

**Comment by AlphaAtlas** [comment]
I have observed this as well. Same prompt on vanilla SD will look distorted and disfigured on AIT.

It doesn't happen in simple tests, but becomes very apparent in more complex prompts, even without any weighting from parentheses. 

I haven't used the AIT backend in a bit, I will refresh the AIT install and post an example if I run into one.
