### ISSUE TITLE
Bug in Frontend View

### ISSUE THREAD

**Issue by mow20** [VoltaML/voltaML-fast-stable-diffusion#63]
### Describe the bug

frontend\src\views\TextToImageView.vue

The width and height are misplaced, so when generating an image, the front sends the width value as height, and viceversa:
![image](https://user-images.githubusercontent.com/6917017/234828062-09452576-b5f7-47a5-9c60-a6137a23729f.png)

### Reproduction

Generate any image with different width and height, and see how the frontend calls the api with the values reversed

### Expected behavior

The frontend should send the correct values from the width and height sliders

### Branch

Experimental

### System Info

Experimental branch

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Stax124** [comment]
Thanks for bringing my attention to this - commit 47a249a will fix this issue, all you need to do is run `git pull` to update if you are on local (the Docker container will probably be released in 3 days with version 0.1.0)
