### ISSUE TITLE
Does this project support the acceleration of AITemplate pipeline?

### ISSUE THREAD

**Issue by zwj536** [VoltaML/voltaML-fast-stable-diffusion#64]
### Is your feature request related to a problem? Please describe.

Does this project support the acceleration of Lora in AITemplate pipeline?

### Describe the solution you'd like

Maybe it needs to "inject" or "swap" the LORAs weights into the already compiled unet.so. Refit API can be used to patch/update the weights of the engine at runtime in TensorRT

### Additional context

Or can anyone share some ideas on how to implement it ？

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
We do not have support for LoRAs on AIT, but they might be able to be compiled with the tokenizer and Unet. It is definitely not planned in the near future as we still have a lot of stuff to finish and fix with PyTorch itself (and AIT takes a lot more time)

Thanks for sharing Refit, we might be adding TRT back at some point - so it might be used at some point.
