### ISSUE TITLE
[Feature]: Tesla A40 support?

### ISSUE THREAD

**Issue by Mfweb** [VoltaML/voltaML-fast-stable-diffusion#66]
### Is your feature request related to a problem? Please describe.

· Graphics card for AITemplate: RTX 40xx, RTX 30xx, H100, A100, A10, A30, V100, T4
It seems that the Tesla A40 is not supported?

### Describe the solution you'd like

I have a Tesla A40, and it seems not to be on the supported list. Can I use it normally, or do I need to wait for support?

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
AIT developers are probably doing this as they want to support GPUs that they have on hand. If you want to try AIT then it should work, but it might require modification of one file - feel free to try, if it doesn't work then come to our discord and ping me (Stax124). I will show you how to fix it.

I will probably fork AIT in the future and add these GPUs myself.
