### ISSUE TITLE
It seems like that the AIT doesn't support dynamic shape ?

### ISSUE THREAD

**Issue by zwj536** [VoltaML/voltaML-fast-stable-diffusion#69]
### Is your feature request related to a problem? Please describe.

When I change the output size of the txt2img, it occurs sth error as belows (I build the ait with runwayml--stable-diffusion-v1-5__512x512x1)
```
// case 1 output size is 64 * 64
...
[18:16:17] model_interface.cu:210: Error: [SetValue] Dimension got value out of bounds; expected value to be in [32, 64], but got 8.

// case 2 output size is 512 * 256
...
  File "/home/quchenxi/test/fastsd/core/aitemplate/src/ait_txt2img.py", line 429, in __call__
    latents = self.scheduler.step(
  File "/home/quchenxi/test/TensorRT/dm_engine/lib/python3.10/site-packages/diffusers/schedulers/scheduling_ddim.py", line 326, in step
    pred_original_sample = (sample - beta_prod_t ** (0.5) * model_output) / alpha_prod_t ** (0.5)
RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 3
```

### Describe the solution you'd like

Maybe it need some work on AITStableDiffusionPipeline before building engines like trt

### Additional context

Do you have the plan to support the dynamic shape on AIT ? Or can you share some ideas about how to make it ?

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
This is not possible as AITemplate does not support Dynamic Shapes yet. For now, the front end will auto-lock your resolution and batch size to mirror the one used when compiling. We had internal discussions about bringing TRT back, but it is not the top priority for now.
