### ISSUE TITLE
[Feature]: add controlnet for SD2.0 model support and ati acceleration capability

### ISSUE THREAD

**Issue by brucelil** [VoltaML/voltaML-fast-stable-diffusion#70]
### Is your feature request related to a problem? Please describe.

When I try to compile ATI for SD2.0 model, there is an error in the second step, I think it is not supported yet

### Describe the solution you'd like

https://huggingface.co/thibaud/controlnet-sd21

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brucelil** [comment]
> Fail on the second AIT step is expected if you used a model that is converted from .ckpt/.safetensors to diffusers format. It should just skip that step if it encounters an error. Other parts of it should still be functional.
> 
> As far as ControlNet goes, I was just working on that when you opened this issue.
I try to compile runwayml/stable-diffusion-v1-5, a sd1.5 model from hugging face, the second step is compiled successfully with the resolution  512*512, but when the resolution is set to 768*576, controlnet unet Compilation failed

**Comment by brucelil** [comment]
> Fail on the second AIT step is expected if you used a model that is converted from .ckpt/.safetensors to diffusers format. It should just skip that step if it encounters an error. Other parts of it should still be functional.
> 
> As far as ControlNet goes, I was just working on that when you opened this issue.

I try to compile runwayml/stable-diffusion-v1-5, a sd1.5 model from hugging face, the second step is compiled successfully with the resolution 512512, but when the resolution is set to 768576, controlnet unet Compilation failed

**Comment by Stax124** [comment]
ControlNets can now be passed as a custom string in the UI, this is available on the experimental branch only for now
