### ISSUE TITLE
[Bug]: Image to image always outputs images with 512X512 resolution

### ISSUE THREAD

**Issue by brucelil** [VoltaML/voltaML-fast-stable-diffusion#71]
### Describe the bug

Image to image always outputs images with 512X512 resolution

### Reproduction

build latest branch

### Expected behavior

Output by setting

### Installation Method

Docker

### Branch

Experimental

### System Info

building with dockerfile

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by Stax124** [comment]
Patched upstream, wait for new version of docker container or build from source (commands can be found in package.json)
