### ISSUE TITLE
After failing to load a model (or the correct one) and trying to load a textual inversion (after getting error), it doesn't reset the LOAD button

### ISSUE THREAD

**Issue by cleverestx** [VoltaML/voltaML-fast-stable-diffusion#80]
### Discussed in https://github.com/VoltaML/voltaML-fast-stable-diffusion/discussions/79

<div type='discussions-op-text'>

<sup>Originally posted by **cleverestx** May 14, 2023</sup>

![image](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/28905253/50a26843-0148-4c7b-8608-4b61c7ef9ad9)

The button is no longer usable even after re-loading the correct model when it tells you 'X model is not loaded', even when the window is closed and re-opened. Please fix this so the LOAD button is restored when loading the asked-for model (or closing and re-opening this window).

Even when loading it properly with the correct model, you can't unload/remove it? It does not appear in the prompt either...the latter would be nice, and some embeddings are for NEGATIVE prompts...how would that work?

Thank you.</div>

**Comment by Stax124** [comment]
I think this behavior might have been patched with some other updates done to the loading system, can you check if this error persists?

**Comment by cleverestx** [comment]
Yes, this does NOT appear to be an issue anymore. Thank you.
