### ISSUE TITLE
[Feature]: add controlnet tile for upscaling

### ISSUE THREAD

**Issue by Katehuuh** [VoltaML/voltaML-fast-stable-diffusion#87]
### Is your feature request related to a problem? Please describe.

Use control_v11f1e_sd15_tile for upscaling? https://github.com/Mikubill/sd-webui-controlnet/issues/1033 & https://github.com/Mikubill/sd-webui-controlnet/discussions/1435

### Describe the solution you'd like

https://youtu.be/3z4MKUqFEUk

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
Added in the latest commit on the experimental branch
