### ISSUE TITLE
[Bug]: Weighted prompts activate with kb shortcut (it shows), but they vanish (don't work) when generating

### ISSUE THREAD

**Issue by cleverestx** [VoltaML/voltaML-fast-stable-diffusion#93]
### Describe the bug

Hold CTRL and press up and down arrow on a keyword and it shows weighting, but when generating, those weights vanish and apparently aren't working.

### Reproduction

Follow the steps in the description to replicate the issue.

### Expected behavior

image should generate and still retain the weights on the keywords set previously.

### Installation Method

Local

### Branch

Experimental

### System Info

Windows 11 Pro
Python 3.10
Ubuntu - WSL installation (latest as of now)

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by gabe56f** [comment]
Are you on Pytorch or AIT?

**Comment by Stax124** [comment]
@gabe56f its UI bug, it is replacing the string in a way that Vue cannot register it. I will handle that.
