### ISSUE TITLE
[Bug]: Linux distributions problems, Ubuntu 23.04

### ISSUE THREAD

**Issue by bkutasi** [VoltaML/voltaML-fast-stable-diffusion#95]
### Describe the bug

Upon launching the manager and running the install on Ubuntu 23.04 but it gives a missing venv python error. U22 LTS works without a problem.

### Reproduction

Install Ubuntu 23.04 (minimal/not minimal doesn't matter i think)

### Expected behavior

Python is working as expected with venvs

### Installation Method

None

### Branch

Main

### System Info

Python 3.11
New install

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] I am writing the issue in English.

**Comment by Stax124** [comment]
I think this was patched already, I will close this for now. If it didn't solve the problem, please reopen this issue.
